# Generated by Django 4.0.1 on 2023-06-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio_Jockey', '0003_alter_audio_jockey_introduction_voice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_jockey',
            name='Introduction_voice',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='audio_jockey',
            name='profile_picture',
            field=models.CharField(default='', max_length=200),
        ),
    ]
